---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Evaluacion Service"
        /opt/fondes/prod/scripts/deployevaluacionservice.sh
