---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando Frontend de Fondes en QA
      shell: |
        echo "Desplegando Frontend"
        /opt/fondes/prod/scripts/deployfrontend.sh
