---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Maestra Service"
        /opt/fondes/prod/scripts/deploymaestraservice.sh
