---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Registration Service"
        /opt/fondes/prod/scripts/deployregistrationservice.sh
