---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Registro Service"
        /opt/fondes/prod/scripts/deployregistroservice.sh
