---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Reporte Service"
        /opt/fondes/prod/scripts/deployreporteservice.sh
